<?xml version="1.0" encoding="utf-8"?><Database Name="QLPizza" Class="QLPizzaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=45.119.85.244;Initial Catalog=QLPizza;User ID=QLPizza" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QLPizzaConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Ban" Member="Bans">
    <Type Name="Ban">
      <Column Name="maBan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="maBanDat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maDonHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tenBan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="trangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Ban_DatBan" Member="DatBans" ThisKey="maBan" OtherKey="maBan" Type="DatBan" />
      <Association Name="Ban_DonHang" Member="DonHangs" ThisKey="maBan" OtherKey="maBan" Type="DonHang" />
    </Type>
  </Table>
  <Table Name="dbo.ChamCong" Member="ChamCongs">
    <Type Name="ChamCong">
      <Column Name="maChamCong" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maNhanVien" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="gioVao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="gioRa" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="NhanVien_ChamCong" Member="NhanVien" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietDonHang" Member="ChiTietDonHangs">
    <Type Name="ChiTietDonHang">
      <Column Name="maChiTiet" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="maDonHang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="maSanPham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thanhTien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="DonHang_ChiTietDonHang" Member="DonHang" ThisKey="maDonHang" OtherKey="maDonHang" Type="DonHang" IsForeignKey="true" />
      <Association Name="SanPham_ChiTietDonHang" Member="SanPham" ThisKey="maSanPham" OtherKey="maSanPham" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DatBan" Member="DatBans">
    <Type Name="DatBan">
      <Column Name="maBanDat" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="maBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maKhachHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tenBan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ngayDat" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="gioDen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Ban_DatBan" Member="Ban" ThisKey="maBan" OtherKey="maBan" Type="Ban" IsForeignKey="true" />
      <Association Name="KhachHang_DatBan" Member="KhachHang" ThisKey="maKhachHang" OtherKey="maKhachHang" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DonHang" Member="DonHangs">
    <Type Name="DonHang">
      <Column Name="maDonHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="maKhachHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngayDatHang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="tongTien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="IsConfirmed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DonHang_ChiTietDonHang" Member="ChiTietDonHangs" ThisKey="maDonHang" OtherKey="maDonHang" Type="ChiTietDonHang" />
      <Association Name="DonHang_GiaoHang" Member="GiaoHangs" ThisKey="maDonHang" OtherKey="maDonHang" Type="GiaoHang" />
      <Association Name="Ban_DonHang" Member="Ban" ThisKey="maBan" OtherKey="maBan" Type="Ban" IsForeignKey="true" />
      <Association Name="KhachHang_DonHang" Member="KhachHang" ThisKey="maKhachHang" OtherKey="maKhachHang" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GiaoHang" Member="GiaoHangs">
    <Type Name="GiaoHang">
      <Column Name="maGiaoHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="maDonHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngayGiao" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="diaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="DonHang_GiaoHang" Member="DonHang" ThisKey="maDonHang" OtherKey="maDonHang" Type="DonHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="maKhachHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="taiKhoan" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="matKhau" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="hoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="soDT" Type="System.String" DbType="NVarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="diaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="KhachHang_DatBan" Member="DatBans" ThisKey="maKhachHang" OtherKey="maKhachHang" Type="DatBan" />
      <Association Name="KhachHang_DonHang" Member="DonHangs" ThisKey="maKhachHang" OtherKey="maKhachHang" Type="DonHang" />
    </Type>
  </Table>
  <Table Name="dbo.KichThuoc" Member="KichThuocs">
    <Type Name="KichThuoc">
      <Column Name="maKichThuoc" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenKichThuoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="gia" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Association Name="KichThuoc_SanPham" Member="SanPhams" ThisKey="maKichThuoc" OtherKey="maKichThuoc" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.Loai" Member="Loais">
    <Type Name="Loai">
      <Column Name="maLoai" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenLoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="moTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Loai_SanPham" Member="SanPhams" ThisKey="maLoai" OtherKey="maLoai" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="maNhanVien" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="taiKhoan" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="matKhau" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="hoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="gioiTinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="soDT" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="chucVu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NhanVien_ChamCong" Member="ChamCongs" ThisKey="maNhanVien" OtherKey="maNhanVien" Type="ChamCong" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="maSanPham" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenSanPham" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="gia" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="mota" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="hinhanh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="maLoai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maKichThuoc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maThanhPhan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SanPham_ChiTietDonHang" Member="ChiTietDonHangs" ThisKey="maSanPham" OtherKey="maSanPham" Type="ChiTietDonHang" />
      <Association Name="SanPham_TonKho" Member="TonKhos" ThisKey="maSanPham" OtherKey="maSanPham" Type="TonKho" />
      <Association Name="KichThuoc_SanPham" Member="KichThuoc" ThisKey="maKichThuoc" OtherKey="maKichThuoc" Type="KichThuoc" IsForeignKey="true" />
      <Association Name="Loai_SanPham" Member="Loai" ThisKey="maLoai" OtherKey="maLoai" Type="Loai" IsForeignKey="true" />
      <Association Name="ThanhPhan_SanPham" Member="ThanhPhan" ThisKey="maThanhPhan" OtherKey="maThanhPhan" Type="ThanhPhan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThanhPhan" Member="ThanhPhans">
    <Type Name="ThanhPhan">
      <Column Name="maThanhPhan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenThanhPhan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="gia" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Association Name="ThanhPhan_SanPham" Member="SanPhams" ThisKey="maThanhPhan" OtherKey="maThanhPhan" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.TonKho" Member="TonKhos">
    <Type Name="TonKho">
      <Column Name="maTonKho" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="maSanPham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tenSanPham" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="soLuongCL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SanPham_TonKho" Member="SanPham" ThisKey="maSanPham" OtherKey="maSanPham" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
</Database>